name: Auto Pull Request

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main # The branch you want to merge into
          title: "[Automated] Update from develop"
          body: "This pull request was automatically created to merge changes from develop to main."
          labels: "automated, update" # Use labels to categorize the PR
          commit-message: "Update from develop"
          branch: "auto-update-from-develop"
          token: ${{ secrets.GITHUB_TOKEN }}
