name: Auto Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "main"
          base: "develop"
          token: "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"
          title: "[Automated] Update from develop"
          body: "This pull request was automatically created to merge changes from develop to main."
