name: Auto Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Check for changes
        id: check_changes
        run: |
          git fetch origin
          git checkout develop
          git diff --exit-code || echo "Changes detected" > changes_detected.txt

      - name: Create a branch for the pull request
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -b update-branch
          git add .
          git commit -m "Automated update"
          git push origin update-branch

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: update-branch
          title: "Automated Pull Request"
          body: "This is an automated pull request created by GitHub Actions."
