name: Auto Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          destination_branch: "main"
          github_token: "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"
          pr_label: "automated, update"
          pr_title: "[Automated] Update from develop"
          pr_body: "This pull request was automatically created to merge changes from develop to main."
