name: Auto Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.test }}
          pr_label: "automated, update"
          pr_title: "[Automated] Update from develop"
          pr_body: "This pull request was automatically created to merge changes from develop to main."
